function getInfo() {
	window.numberOfQuestions = 	10;
	window.currentSlide = 		0;
	window.currentScore = 		0;
	window.title = 				"DINOSAURS TRIVIA";
	window.questions = [		"WHEN DID THE DINOSAURS WENT EXTINCT", 
								"WHAT ERA DID THE DINOSAUR LIVED IN",
								"WHICH ONE OF THESE DINOSAURS WERE NOT ACTUALLY A DINOSAURS",
								"WHAT DOES THE WORD TYRANNOSAURUS REX MEAN", 
								"HOW MANY DIFFERENT SPIECES OF DINOSAURS WERE THERE", 
								"WHICH DINOSAUR WERE THE LARGEST DINOSAUR TO HAD EVER LIVED",
								"WHICH DINOSAUR HAD THE SMALLEST BRAIN FOR ITS BODY SIZE",
								"WHICH CONTINENTS HAVE DINOSAUR FOSSILS FOUND ON",
								"HOW ARE THE TWO GROUP OF DINOSAURS DIFFERENTIATED",
								"WHICH DINOSAUR WAS THE LARGEST CARNIVOROUS DINOSAUR" ];
	window.correctAnswer = [ 	"D", "C", "B", "A", "E", "D", "B", "E", "C", "E" ]; 
	window.answerA = [ 			"120 MILLIONS OF YEARS AGO", 
								"PRECAMBRIAN", 
								"ALLOSAURUS", 
								"KING OF THE TYRANT", 
								"200",
								"BRACHIOSAURUS",
								"VELOCIRAPTOR",
								"SOUTH AMERICA",
								"TEETH",
								"CARNOTAURUS" ];
	window.answerB = [ 			"70 MILLIONS OF YEARS AGO", 
								"PALAEOZOIC", 
								"PTERODACTYL", 
								"LORD OF THE LAND",
								"10",
								"TRICERATOPS",
								"STEGOSAURUS",
								"ANTARCTICA",
								"DIET",
								"GIGANOTOSAURUS"  ];
	window.answerC = [ 			"90 MILLIONS OF YEARS AGO",
								"MESOZOIC",
								"T-REX", 
								"BIG TOOTH", 
								"1000",
								"UTAHRAPTOR",
								"ANKYLOSAURUS",
								"ASIA",
								"HIP BONE",
								"ALLOSAURUS" ];
	window.answerD = [ 			"65 MILLIONS OF YEARS AGO",  
								"CENOZOIC",
								"STEGOSAURUS", 
								"FISH EATER",
								"50",
								"ARGENTINOSAURUS",
								"SPINOSAURUS",
								"NORTH AMERICA",
								"CLAWS",
								"T-REX" ];
	window.answerE = [ 			"10 MILLIONS OF YEARS AGO", 
								"HOLOCENE", 
								"BRACHIOSAURUS",
								"GIANT KILLER", 
								"700",
								"T-REX",
								"CARNOTAURUS",
								"ALL OF THE CONTINENTS",
								"COLOR",
								"SPINOSAURUS" ];
	window.response = [ 		"THE DINOSAURS WENT EXTINCT 65 MILLIONS OF YEARS AGO", 
								"DINOSAURS LIVED IN THE MESZOIC ERA WHICH HAD THREE PERIOD, TRIASSIC, JURASSIC, AND CRETACEOUS", 
								"THE PTERODACTYL WERE NOT ACTUALLY A DINOSAUR BUT WERE 'FLYING DINOSAURS'", 
								"TYRANNOSAURUS REX MEANS IN GREEK 'KING OF THE TYRANT'", 
								"THERE WERE 700 DIFFERENT SPEIECES OF DINOSAURS",
								"THE ARGENTINOSAURUS WERE THE LARGEST LAND DINOSAUR. RANGING FROM 110,000 TO 220,000LBS AND 72 TO 110FT",
								"THE STEGOSAURUS HAS THE SMALLEST BRAIN WHICH WAS THE SIZE OF A WALNUT",
								"DINOSAUR FOSSILS HAD BEEN FOUND ON ALL OF THE CONTINENTS EVEN IN THE ANTARCTICA",
								"DINOSAURS WERE DIFFERENTIATED BASED ON THEIR HIP BONE. ORNITHISCHIAN 'BIRD-HIPPED' AND SAURISCHIA 'LIZARD-HIPPED'",
								"THE SPINOSAURUS WERE THE LARGEST OF ALL OF THE CARNIVOROUS DINOSAURS. RANGING FROM 14,000 TO 17,000LBS AND 14 TO 23FT" ];
							
}						